name: 01 - Building Blocks # The name of the workflow

on: push
# This is the trigger of the workflow
# Whenever we push to the online repository, then execute this workflow

jobs: # This is what jobs are included in our workflow
    # The Linux runner is ususally the cheapest and most widely used
    echo-hello: 
        runs-on: ubuntu-latest
        steps: 
            - name: Say Hello
              run: echo "Hello, World!"
    echo-goodbye: 
        runs-on: ubuntu-latest
        steps:
            - name: Successful step
              run: | # The pipe is required for multiple lines
                echo "I will fail"
                exit 0
            - name: Say Goodbye
              run: echo "Goodbye!"

